### ISSUE TITLE
wrong package name in documentation?

### ISSUE THREAD

**Issue by sleungcy** [TobiasWalle/isomorphic-style-loader-utils#1]
Thanks for this amazing gem.
The docs is referring to isomorphic-style-loader-decorator but its called isomorphic-style-loader-utils on npmjs

**Comment by tobias-walle** [comment]
Hello sleungcy
Thank you for creating this issue. I renamed the package once and forgot to correct the name.
I fixed the README and will publish a new version soon.

Can you close this issue if you are happy with the change?
Thank you!

**Comment by sleungcy** [comment]
:+1:
